# Generated by Django 5.2.7 on 2025-10-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_admin_groups_admin_is_active_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cafe_staff',
            field=models.BooleanField(default=False),
        ),
    ]
