# Generated by Django 5.2.7 on 2025-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff_member', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='staff_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
