# Generated by Django 5.2.7 on 2025-10-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='temp', upload_to='menu_images/'),
            preserve_default=False,
        ),
    ]