# Generated by Django 5.2.7 on 2025-10-18 22:31

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20251019_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to=menu.models.menu_image_filename),
        ),
    ]
